name: CI # name of the action (displayed in the github interface)

run-name: ${{ github.actor }} running CI

on: # event list
  push:
    branches: [main]
  pull_request: # on a pull request to each of these branches
    branches:
      - main
      - development
      - staging
      - production

env: # environment variables (available in any part of the action)
  NODE_VERSION: 19

jobs: # list of things to do
  lint:
    name: Linting # job name (unique id)
    runs-on: ubuntu-latest # on which machine to run
    steps: # list of steps
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm ci

      - name: Code Linting
        run: npm run lint

  test:
    name: Test # job name (unique id)
    runs-on: ubuntu-latest # on which machine to run
    steps: # list of steps
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm run test
